In [1]:
import numpy as np

A = [[4,1,1.6,3.4,4.1,3.9,1.9,1.3,1.7],
[2,3,1.8,3.2,3.3,3.7,2.7,1.9,2.1],
[-2,2,0.2,-0.2,-0.8,-0.2,0.8,0.6,0.4],
[7,5,4.1,7.9,8.8,9.1,5.6,3.9,4.6],
[-1,6,2.1,2.9,2.1,3.4,3.9,2.8,2.7],
[2,7,3.4,5.6,5.3,6.5,5.5,3.9,4.1],
[4,1,1.6,3.4,4.1,3.9,1.9,1.3,1.7],
[5,3,2.7,5.3,6,6.1,3.6,2.5,3],
[6,-4,0.2,1.8,3.4,2,-1,-0.8,-0.2],
[1,7,3.1,4.9,4.4,5.7,5.2,3.7,3.8]]

U1, S1, VT1 = np.linalg.svd(A,full_matrices=False) #to get the correct dimensions
S = S1
S1 = np.diag(S1)
App1 = U1 @ S1 @ VT1
print(App1)
print('U1 : ', U1)
print('S1 : ', S1)
print('VT1 : ', VT1)

[[ 4.   1.   1.6  3.4  4.1  3.9  1.9  1.3  1.7]
 [ 2.   3.   1.8  3.2  3.3  3.7  2.7  1.9  2.1]
 [-2.   2.   0.2 -0.2 -0.8 -0.2  0.8  0.6  0.4]
 [ 7.   5.   4.1  7.9  8.8  9.1  5.6  3.9  4.6]
 [-1.   6.   2.1  2.9  2.1  3.4  3.9  2.8  2.7]
 [ 2.   7.   3.4  5.6  5.3  6.5  5.5  3.9  4.1]
 [ 4.   1.   1.6  3.4  4.1  3.9  1.9  1.3  1.7]
 [ 5.   3.   2.7  5.3  6.   6.1  3.6  2.5  3. ]
 [ 6.  -4.   0.2  1.8  3.4  2.  -1.  -0.8 -0.2]
 [ 1.   7.   3.1  4.9  4.4  5.7  5.2  3.7  3.8]]
U1 :  [[-0.22972962  0.22429369 -0.92807988 -0.0748224   0.14117146 -0.01251758
  -0.03888105  0.02415076 -0.06141381]
 [-0.23447768 -0.02917493  0.20999903 -0.60963399  0.49170745  0.17170371
  -0.36500544  0.25070633 -0.24687662]
 [-0.00474806 -0.25346863 -0.0956192   0.22748883  0.15499439  0.16140558
   0.04722713 -0.1298346  -0.35167883]
 [-0.55752357  0.20879565  0.12279211  0.22323043 -0.13527546  0.32258136
   0.22692384  0.5620245   0.2555235 ]
 [-0.24159978 -0.40937787 -0.05762761 -0.48822795 -0.28291254

In [2]:
u1 = U1[:, 0:1]
v1 = VT1[0:1,:]
res1 = S[0]*(u1 @ v1)
print(res1)

[[2.19014961 2.72004732 1.74506381 3.16513312 3.33115831 3.65615281
  2.56107801 1.79805358 2.01706854]
 [2.23541572 2.77626539 1.78113087 3.23055024 3.40000684 3.73171835
  2.61401049 1.83521584 2.05875741]
 [0.04526611 0.05621807 0.03606706 0.06541712 0.06884854 0.07556554
  0.05293248 0.03716226 0.04168887]
 [5.315205   6.60119706 4.23504032 7.68136173 8.08428303 8.87300194
  6.21539944 4.36363953 4.89516003]
 [2.30331489 2.86059248 1.83523146 3.32867591 3.50327964 3.84506665
  2.69340921 1.89095922 2.12129071]
 [4.05996119 5.04225215 3.23488922 5.86732412 6.17509114 6.77754545
  4.74756486 3.33311831 3.73911443]
 [2.19014961 2.72004732 1.74506381 3.16513312 3.33115831 3.65615281
  2.56107801 1.79805358 2.01706854]
 [3.53592565 4.39142836 2.81734904 5.11000497 5.37804726 5.90274037
  4.13477755 2.90289931 3.25649187]
 [0.77647439 0.96433918 0.61867799 1.12213558 1.18099654 1.29621694
  0.90797975 0.63746447 0.71511191]
 [3.62645788 4.50386449 2.88948316 5.24083921 5.51574434 6.05387

In [14]:

u2 = U1[:, 1:2]
v2 = VT1[1:2,:]

res2 = S[1]*(u2 @ v2)
print(res2)

[[ 1.80985039 -1.72004732 -0.14506381  0.23486688  0.76884169  0.24384719
  -0.66107801 -0.49805358 -0.31706854]
 [-0.23541572  0.22373461  0.01886913 -0.03055024 -0.10000684 -0.03171835
   0.08598951  0.06478416  0.04124259]
 [-2.04526611  1.94378193  0.16393294 -0.26541712 -0.86884854 -0.27556554
   0.74706752  0.56283774  0.35831113]
 [ 1.684795   -1.60119706 -0.13504032  0.21863827  0.71571697  0.22699806
  -0.61539944 -0.46363953 -0.29516003]
 [-3.30331489  3.13940752  0.26476854 -0.42867591 -1.40327964 -0.44506665
   1.20659079  0.90904078  0.57870929]
 [-2.05996119  1.95774785  0.16511078 -0.26732412 -0.87509114 -0.27754545
   0.75243514  0.56688169  0.36088557]
 [ 1.80985039 -1.72004732 -0.14506381  0.23486688  0.76884169  0.24384719
  -0.66107801 -0.49805358 -0.31706854]
 [ 1.46407435 -1.39142836 -0.11734904  0.18999503  0.62195274  0.19725963
  -0.53477755 -0.40289931 -0.25649187]
 [ 5.22352561 -4.96433918 -0.41867799  0.67786442  2.21900346  0.70378306
  -1.90797975 -1.43746

In [5]:
u3 = U1[:, 2:3]
v3 = VT1[2:3,:]
res3 = S[2]*(u3 @ v3)
print(res3)

[[ 5.03070432e-16  3.02582802e-16  6.14837625e-17  2.05961000e-15
  -1.09296206e-15 -1.11155644e-15 -3.92793492e-16 -5.55628582e-17
   1.28730203e-16]
 [-1.13831045e-16 -6.84661916e-17 -1.39120896e-17 -4.66033271e-16
   2.47307346e-16  2.51514745e-16  8.88783972e-17  1.25723513e-17
  -2.91281152e-17]
 [ 5.18308759e-17  3.11748230e-17  6.33461453e-18  2.12199692e-16
  -1.12606858e-16 -1.14522620e-16 -4.04691460e-17 -5.72458930e-18
   1.32629523e-17]
 [-6.65600904e-17 -4.00340338e-17 -8.13477504e-18 -2.72502257e-16
   1.44607293e-16  1.47067473e-16  5.19696024e-17  7.35139383e-18
  -1.70319967e-17]
 [ 3.12373380e-17  1.87883857e-17  3.81773397e-18  1.27888124e-16
  -6.78656966e-17 -6.90202845e-17 -2.43898713e-17 -3.45008507e-18
   7.99329200e-18]
 [-5.74067362e-17 -3.45285472e-17 -7.01607949e-18 -2.35027704e-16
   1.24720875e-16  1.26842731e-16  4.48227345e-17  6.34042899e-18
  -1.46897538e-17]
 [-4.18558126e-17 -2.51751013e-17 -5.11549215e-18 -1.71360996e-16
   9.09352095e-17  9.2482275

In [6]:
apx = res1 + res2
print(apx)

[[ 4.   1.   1.6  3.4  4.1  3.9  1.9  1.3  1.7]
 [ 2.   3.   1.8  3.2  3.3  3.7  2.7  1.9  2.1]
 [-2.   2.   0.2 -0.2 -0.8 -0.2  0.8  0.6  0.4]
 [ 7.   5.   4.1  7.9  8.8  9.1  5.6  3.9  4.6]
 [-1.   6.   2.1  2.9  2.1  3.4  3.9  2.8  2.7]
 [ 2.   7.   3.4  5.6  5.3  6.5  5.5  3.9  4.1]
 [ 4.   1.   1.6  3.4  4.1  3.9  1.9  1.3  1.7]
 [ 5.   3.   2.7  5.3  6.   6.1  3.6  2.5  3. ]
 [ 6.  -4.   0.2  1.8  3.4  2.  -1.  -0.8 -0.2]
 [ 1.   7.   3.1  4.9  4.4  5.7  5.2  3.7  3.8]]


In [7]:

u4 = U1[:, 3:4]
v4 = VT1[3:4,:]
res4 = S[3]*(u4 @ v4)
print(res4)

[[ 2.78130400e-17 -4.55630494e-17  2.59632503e-17 -2.36604354e-17
  -6.54521379e-17  3.41729415e-18  6.14631840e-17  3.31582357e-17
   4.02092537e-17]
 [ 2.26613624e-16 -3.71236216e-16  2.11542005e-16 -1.92779251e-16
  -5.33287485e-16  2.78432495e-17  5.00786496e-16  2.70164928e-16
   3.27614842e-16]
 [-8.45623249e-17  1.38529171e-16 -7.89382536e-17  7.19368119e-17
   1.98999640e-16 -1.03898868e-17 -1.86871688e-16 -1.00813773e-16
  -1.22251576e-16]
 [-8.29793910e-17  1.35936024e-16 -7.74605975e-17  7.05902167e-17
   1.95274538e-16 -1.01953971e-17 -1.83373611e-16 -9.89266259e-17
  -1.19963132e-16]
 [ 1.81484478e-16 -2.97306092e-16  1.69414308e-16 -1.54388077e-16
  -4.27085535e-16  2.22983840e-17  4.01056981e-16  2.16362724e-16
   2.62371730e-16]
 [-1.82756272e-16  2.99389532e-16 -1.70601517e-16  1.55469987e-16
   4.30078434e-16 -2.24546450e-17 -4.03867479e-16 -2.17878935e-16
  -2.64210360e-16]
 [ 5.97776040e-17 -9.79270846e-17  5.58019150e-17 -5.08525547e-17
  -1.40674014e-16  7.3446720

In [8]:
u5 = U1[:, 4:5]
v5 = VT1[4:5,:]
res5 = S[4]*(u5 @ v5)
print(res5)

[[ 9.47911609e-17  9.22884142e-17 -2.27587528e-17 -6.30308659e-17
  -5.25399225e-17  2.05916345e-17 -4.73380327e-17 -1.39647572e-17
   1.32168502e-17]
 [ 3.30162481e-16  3.21445286e-16 -7.92699045e-17 -2.19539743e-16
  -1.82999248e-16  7.17217204e-17 -1.64880799e-16 -4.86399665e-17
   4.60349680e-17]
 [ 1.04072722e-16  1.01324917e-16 -2.49871963e-17 -6.92025894e-17
  -5.76844159e-17  2.26078828e-17 -5.19731784e-17 -1.53321289e-17
   1.45109899e-17]
 [-9.08322219e-17 -8.84340021e-17  2.18082368e-17  6.03983910e-17
   5.03456003e-17 -1.97316279e-17  4.53609667e-17  1.33815212e-17
  -1.26648504e-17]
 [-1.89964797e-16 -1.84949206e-16  4.56093355e-17  1.26316057e-16
   1.05291840e-16 -4.12663548e-17  9.48670712e-17  2.79858613e-17
  -2.64870295e-17]
 [ 3.05113392e-16  2.97057562e-16 -7.32557782e-17 -2.02883488e-16
  -1.69115283e-16  6.62802670e-17 -1.52371462e-16 -4.49497022e-17
   4.25423422e-17]
 [ 7.53670349e-17  7.33771384e-17 -1.80951441e-17 -5.01148992e-17
  -4.17737069e-17  1.6372100

In [9]:
u6 = U1[:, 5:6]
v6 = VT1[5:6,:]
res6 = S[5]*(u6 @ v6)
print(res6)

[[-2.72305458e-18 -1.74656945e-18 -8.64343048e-19  1.77011713e-18
  -2.95036247e-18  6.12407984e-18 -3.69427721e-18 -1.24887548e-18
   2.85798706e-18]
 [ 3.73521496e-17  2.39576995e-17  1.18561967e-17 -2.42807031e-17
   4.04701328e-17 -8.40040255e-17  5.06744140e-17  1.71308295e-17
  -3.92030189e-17]
 [ 3.51119107e-17  2.25208084e-17  1.11451075e-17 -2.28244395e-17
   3.80428892e-17 -7.89657857e-17  4.76351567e-17  1.61033879e-17
  -3.68517720e-17]
 [ 7.01738321e-17  4.50095537e-17  2.22743475e-17 -4.56163836e-17
   7.60316163e-17 -1.57819147e-16  9.52024947e-17  3.21838492e-17
  -7.36510776e-17]
 [-9.10630364e-17 -5.84079065e-17 -2.89049301e-17  5.91953763e-17
  -9.86645539e-17  2.04798431e-16 -1.23542181e-16 -4.17642723e-17
   9.55753813e-17]
 [-9.79827229e-17 -6.28461992e-17 -3.11013543e-17  6.36935071e-17
  -1.06161864e-16  2.20360628e-16 -1.32929888e-16 -4.49378506e-17
   1.02837951e-16]
 [-7.64627497e-17 -4.90432707e-17 -2.42705551e-17  4.97044841e-17
  -8.28455034e-17  1.7196276

In [10]:
u7 = U1[:, 6:7]
v7 = VT1[6:7,:]
res7 = S[6]*(u7 @ v7)
print(res7)

[[ 7.04666013e-19  5.72307234e-19  2.75045345e-18  2.07631785e-18
  -5.65665744e-18  7.12081041e-18  2.64634464e-18  2.26609082e-18
  -1.61200091e-17]
 [ 6.61522628e-18  5.37267555e-18  2.58205612e-17  1.94919468e-17
  -5.31032692e-17  6.68483669e-17  2.48432141e-17  2.12734874e-17
  -1.51330568e-16]
 [-8.55927388e-19 -6.95156894e-19 -3.34085708e-18 -2.52201366e-18
   6.87089761e-18 -8.64934102e-18 -3.21440061e-18 -2.75252270e-18
   1.95802792e-17]
 [-4.11268542e-18 -3.34019177e-18 -1.60526400e-17 -1.21181411e-17
   3.30142963e-17 -4.15596220e-17 -1.54450234e-17 -1.32257247e-17
   9.40821967e-17]
 [-9.15767930e-18 -7.43757471e-18 -3.57442677e-17 -2.69833547e-17
   7.35126341e-17 -9.25404332e-17 -3.43912934e-17 -2.94496011e-17
   2.09491973e-16]
 [ 1.08044221e-19  8.77500666e-20  4.21718369e-19  3.18355279e-19
  -8.67317477e-19  1.09181144e-18  4.05755693e-19  3.47452572e-19
  -2.47163025e-18]
 [ 4.08064294e-18  3.31416790e-18  1.59275717e-17  1.20237270e-17
  -3.27570776e-17  4.1235825

In [11]:
u8 = U1[:, 7:8]
v8 = VT1[7:8,:]
res8 = S[7]*(u8 @ v8)
print(res8)

[[ 2.04690015e-19 -4.51569777e-19 -5.87698394e-18  5.36398714e-19
   1.73651329e-19  1.78649091e-19  7.26019939e-20  4.68753621e-18
  -2.51890811e-19]
 [ 2.12486435e-18 -4.68769579e-18 -6.10083187e-17  5.56829558e-18
   1.80265520e-18  1.85453641e-18  7.53673250e-19  4.86607937e-17
  -2.61485058e-18]
 [-1.10041461e-18  2.42764152e-18  3.15946969e-17 -2.88368234e-18
  -9.33550469e-19 -9.60418465e-19 -3.90308705e-19 -2.52002196e-17
   1.35416634e-18]
 [ 4.76344499e-18 -1.05087090e-17 -1.36766269e-16  1.24828061e-17
   4.04112802e-18  4.15743347e-18  1.68955776e-18  1.09086029e-16
  -5.86187861e-18]
 [ 7.83055254e-19 -1.72751019e-18 -2.24827926e-17  2.05202893e-18
   6.64314700e-19  6.83433971e-19  2.77743752e-19  1.79324813e-17
  -9.63625036e-19]
 [-3.14000640e-19  6.92721622e-19  9.01547015e-18 -8.22851763e-19
  -2.66386363e-19 -2.74053080e-19 -1.11373643e-19 -7.19082155e-18
   3.86408081e-19]
 [-2.92943443e-18  6.46267016e-18  8.41088369e-17 -7.67670499e-18
  -2.48522227e-18 -2.5567480

In [12]:

u9 = U1[:, 8:9]
v9 = VT1[8:9,:]
res9 = S[8]*(u9 @ v9)
print(res9)


[[ 4.07780764e-20  6.84344556e-20 -7.47373357e-19  1.56325984e-19
  -9.91796904e-20  1.40526564e-19  8.20041745e-19 -9.64868931e-19
  -7.30841620e-21]
 [ 1.63923301e-19  2.75098848e-19 -3.00435720e-18  6.28412948e-19
  -3.98691249e-19  5.64901051e-19  3.29647598e-18 -3.87866505e-18
  -2.93790147e-20]
 [ 2.33510790e-19  3.91881745e-19 -4.27974437e-18  8.95182096e-19
  -5.67940665e-19  8.04708604e-19  4.69587122e-18 -5.52520682e-18
  -4.18507735e-20]
 [-1.69664732e-19 -2.84734215e-19  3.10958514e-18 -6.50423181e-19
   4.12655454e-19 -5.84686772e-19 -3.41193541e-18  4.01451572e-18
   3.04080179e-20]
 [ 4.59673267e-20  7.71431429e-20 -8.42481017e-19  1.76219385e-19
  -1.11800890e-19  1.58409397e-19  9.24396884e-19 -1.08765418e-18
  -8.23845518e-21]
 [ 9.19625229e-20  1.54333057e-19 -1.68547282e-18  3.52545611e-19
  -2.23669563e-19  3.16914835e-19  1.84935422e-18 -2.17596780e-18
  -1.64819053e-20]
 [-4.20676104e-19 -7.05985733e-19  7.71007708e-18 -1.61269514e-18
   1.02316071e-18 -1.4497046

In [16]:
difference = A - apx
print(difference)

[[ 1.33226763e-15 -1.33226763e-15 -2.22044605e-16 -8.88178420e-16
   0.00000000e+00  8.88178420e-16 -4.44089210e-16 -6.66133815e-16
  -4.44089210e-16]
 [ 2.22044605e-16  0.00000000e+00  2.22044605e-16  0.00000000e+00
   0.00000000e+00  8.88178420e-16  8.88178420e-16 -2.22044605e-16
   4.44089210e-16]
 [-6.66133815e-16  6.66133815e-16  1.66533454e-16  2.77555756e-16
  -8.88178420e-16 -9.99200722e-16  2.22044605e-16  2.22044605e-16
   1.66533454e-16]
 [ 8.88178420e-16  8.88178420e-16  0.00000000e+00  0.00000000e+00
   3.55271368e-15  3.55271368e-15  8.88178420e-16 -4.44089210e-16
   1.77635684e-15]
 [-2.22044605e-15  3.55271368e-15  8.88178420e-16  1.33226763e-15
  -4.44089210e-16  0.00000000e+00  2.22044605e-15  1.33226763e-15
   1.77635684e-15]
 [-4.44089210e-16  0.00000000e+00  4.44089210e-16  0.00000000e+00
  -8.88178420e-16  0.00000000e+00  1.77635684e-15  0.00000000e+00
   0.00000000e+00]
 [ 8.88178420e-16 -4.44089210e-16  2.22044605e-16 -4.44089210e-16
   8.88178420e-16  1.7763568